# Generated by Django 3.0.7 on 2020-07-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200706_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='handshape',
            name='base',
            field=models.CharField(default='', max_length=10, verbose_name='Base Form'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handshape',
            name='fingerspecs',
            field=models.CharField(max_length=10, null=True, verbose_name='Finger Specifications'),
        ),
        migrations.AlterField(
            model_name='handshape',
            name='transcription',
            field=models.CharField(max_length=20, verbose_name='Transcription'),
        ),
    ]
