# Generated by Django 3.0.7 on 2020-08-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200802_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handshape',
            name='bend1',
        ),
        migrations.RemoveField(
            model_name='handshape',
            name='bend2',
        ),
        migrations.RemoveField(
            model_name='handshape',
            name='bend3',
        ),
        migrations.RemoveField(
            model_name='handshape',
            name='bend4',
        ),
        migrations.RemoveField(
            model_name='handshape',
            name='bend5',
        ),
        migrations.AddField(
            model_name='handshape',
            name='bend1_1',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='handshape',
            name='bend1_2',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='handshape',
            name='bend1_3',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='handshape',
            name='bend1_4',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='handshape',
            name='bend1_5',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='handshape',
            name='bend2_1',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='handshape',
            name='bend2_2',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='handshape',
            name='bend2_3',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='handshape',
            name='bend2_4',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='handshape',
            name='bend3_1',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='handshape',
            name='bend3_2',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='handshape',
            name='bend3_3',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='handshape',
            name='bend3_4',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='handshape',
            name='bend4_1',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='handshape',
            name='bend4_2',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='handshape',
            name='bend4_3',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='handshape',
            name='bend4_4',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='handshape',
            name='bend5_1',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='handshape',
            name='bend5_2',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='handshape',
            name='bend5_3',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='handshape',
            name='bend5_4',
            field=models.CharField(default='', max_length=5),
        ),
    ]
