# Generated by Django 3.0.7 on 2020-08-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20200802_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handshape',
            name='handshape',
            field=models.CharField(default='None', max_length=20, verbose_name='Handshape'),
        ),
        migrations.AlterField(
            model_name='handshape',
            name='mainbend',
            field=models.CharField(default='None', max_length=20, verbose_name='Main Bend'),
        ),
        migrations.AlterField(
            model_name='handshape',
            name='specialfingers',
            field=models.CharField(default='None', max_length=20, verbose_name='Special Fingers'),
        ),
        migrations.AlterField(
            model_name='handshape',
            name='thumbpos',
            field=models.CharField(default='None', max_length=20, verbose_name='Thumb Position'),
        ),
    ]
