# Generated by Django 3.0.7 on 2020-08-05 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_handshape_sigml'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('lhs', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='lhs_sign_set', to='inventory.Handshape', verbose_name='Left Handshape')),
                ('rhs', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='rhs_sign_set', to='inventory.Handshape', verbose_name='Right Handshape')),
            ],
        ),
    ]
