# Generated by Django 3.0.7 on 2020-08-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='sigml',
            field=models.TextField(default='<sigml></sigml>'),
        ),
    ]
