# Generated by Django 3.0.7 on 2020-08-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_sign_sigml'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign',
            old_name='rhs',
            new_name='hs',
        ),
        migrations.AddField(
            model_name='sign',
            name='efd',
            field=models.CharField(default='', max_length=5, verbose_name='Right External Finger Direction'),
        ),
        migrations.AddField(
            model_name='sign',
            name='lefd',
            field=models.CharField(default='', max_length=5, verbose_name='Left External Finger Direction'),
        ),
        migrations.AddField(
            model_name='sign',
            name='lloc',
            field=models.CharField(default='', max_length=20, verbose_name='Left Hand Location'),
        ),
        migrations.AddField(
            model_name='sign',
            name='lloc_contact',
            field=models.CharField(default='', max_length=20, verbose_name='Left Hand Location Contact'),
        ),
        migrations.AddField(
            model_name='sign',
            name='lloc_side',
            field=models.CharField(default='', max_length=20, verbose_name='Left Hand Location Side'),
        ),
        migrations.AddField(
            model_name='sign',
            name='loc',
            field=models.CharField(default='', max_length=20, verbose_name='Right Hand Location'),
        ),
        migrations.AddField(
            model_name='sign',
            name='loc_contact',
            field=models.CharField(default='', max_length=20, verbose_name='Right Hand Location Contact'),
        ),
        migrations.AddField(
            model_name='sign',
            name='loc_side',
            field=models.CharField(default='', max_length=20, verbose_name='Right Hand Location Side'),
        ),
        migrations.AddField(
            model_name='sign',
            name='lori',
            field=models.CharField(default='', max_length=5, verbose_name='Left Palm Orientation'),
        ),
        migrations.AddField(
            model_name='sign',
            name='ori',
            field=models.CharField(default='', max_length=5, verbose_name='Right Palm Orientation'),
        ),
        migrations.AddField(
            model_name='sign',
            name='twohanded',
            field=models.BooleanField(default=False),
        ),
    ]
