# Generated by Django 3.0.7 on 2020-08-07 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20200805_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign',
            old_name='loc_contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='sign',
            old_name='lloc_contact',
            new_name='lcontact',
        ),
        migrations.RenameField(
            model_name='sign',
            old_name='lloc_side',
            new_name='lside',
        ),
        migrations.RenameField(
            model_name='sign',
            old_name='loc_side',
            new_name='side',
        ),
    ]
