# Generated by Django 3.0.7 on 2020-08-13 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20200813_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sign',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='sign',
            old_name='lefd',
            new_name='leftFingerDirection',
        ),
        migrations.RenameField(
            model_name='sign',
            old_name='lloc',
            new_name='leftLocation',
        ),
        migrations.RenameField(
            model_name='sign',
            old_name='lside',
            new_name='leftLocationContact',
        ),
        migrations.RenameField(
            model_name='sign',
            old_name='lcontact',
            new_name='leftLocationSide',
        ),
        migrations.RenameField(
            model_name='sign',
            old_name='lori',
            new_name='leftPalmOrientation',
        ),
        migrations.RenameField(
            model_name='sign',
            old_name='efd',
            new_name='rightFingerDirection',
        ),
        migrations.RenameField(
            model_name='sign',
            old_name='loc',
            new_name='rightLocation',
        ),
        migrations.RenameField(
            model_name='sign',
            old_name='contact',
            new_name='rightLocationContact',
        ),
        migrations.RenameField(
            model_name='sign',
            old_name='side',
            new_name='rightLocationSide',
        ),
        migrations.RenameField(
            model_name='sign',
            old_name='ori',
            new_name='rightPalmOrientation',
        ),
        migrations.RenameField(
            model_name='sign',
            old_name='twohanded',
            new_name='twoHanded',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='hs',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='lhs',
        ),
        migrations.AddField(
            model_name='sign',
            name='leftHandshape',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='leftHandshape_sign_set', to='inventory.Handshape', verbose_name='Left Handshape'),
        ),
        migrations.AddField(
            model_name='sign',
            name='locationType',
            field=models.CharField(default='', max_length=5, verbose_name='Location Type'),
        ),
        migrations.AddField(
            model_name='sign',
            name='rightHandshape',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='rightHandshape_sign_set', to='inventory.Handshape', verbose_name='Right Handshape'),
        ),
    ]
