# Generated by Django 3.0.7 on 2020-08-13 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20200813_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='leftHandshape',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='leftHandshape_sign_set', to='inventory.Handshape', verbose_name='Left Handshape'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='rightHandshape',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='rightHandshape_sign_set', to='inventory.Handshape', verbose_name='Right Handshape'),
        ),
    ]
