# Generated by Django 3.0.7 on 2020-08-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20200813_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='constellationContact',
            field=models.CharField(default='', max_length=20, verbose_name='Constellation Contact'),
        ),
        migrations.AddField(
            model_name='sign',
            name='constellationLocation',
            field=models.CharField(default='', max_length=20, verbose_name='Constellation Location'),
        ),
        migrations.AddField(
            model_name='sign',
            name='constellationLocationContact',
            field=models.CharField(default='', max_length=20, verbose_name='Constellation Location Contact'),
        ),
        migrations.AddField(
            model_name='sign',
            name='constellationLocationSide',
            field=models.CharField(default='', max_length=20, verbose_name='Constellation Location Side'),
        ),
        migrations.AddField(
            model_name='sign',
            name='leftContactFinger',
            field=models.CharField(default='', max_length=20, verbose_name='Right Contact Side'),
        ),
        migrations.AddField(
            model_name='sign',
            name='leftContactPart',
            field=models.CharField(default='', max_length=20, verbose_name='Right Contact Side'),
        ),
        migrations.AddField(
            model_name='sign',
            name='leftContactSide',
            field=models.CharField(default='', max_length=20, verbose_name='Right Contact Side'),
        ),
        migrations.AddField(
            model_name='sign',
            name='leftContactType',
            field=models.CharField(default='', max_length=20, verbose_name='Left Contact Type'),
        ),
        migrations.AddField(
            model_name='sign',
            name='rightContactFinger',
            field=models.CharField(default='', max_length=5, verbose_name='Constellation Location Contact'),
        ),
        migrations.AddField(
            model_name='sign',
            name='rightContactPart',
            field=models.CharField(default='', max_length=20, verbose_name='Right Contact Part'),
        ),
        migrations.AddField(
            model_name='sign',
            name='rightContactSide',
            field=models.CharField(default='', max_length=20, verbose_name='Right Contact Side'),
        ),
        migrations.AddField(
            model_name='sign',
            name='rightContactType',
            field=models.CharField(default='', max_length=20, verbose_name='Right Contact Type'),
        ),
    ]
