# Generated by Django 3.0.7 on 2020-09-17 13:11

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20200917_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='leftMotionTags',
            field=django_mysql.models.ListTextField(models.CharField(max_length=500), default=[], size=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sign',
            name='leftTargetConfigs',
            field=django_mysql.models.ListTextField(models.CharField(max_length=500), default=[], size=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sign',
            name='leftTargetLocs',
            field=django_mysql.models.ListTextField(models.CharField(max_length=500), default=[], size=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sign',
            name='rightMotionTags',
            field=django_mysql.models.ListTextField(models.CharField(max_length=500), default=[], size=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sign',
            name='rightTargetConfigs',
            field=django_mysql.models.ListTextField(models.CharField(max_length=500), default=[], size=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sign',
            name='rightTargetLocs',
            field=django_mysql.models.ListTextField(models.CharField(max_length=500), default=[], size=10),
            preserve_default=False,
        ),
    ]
