# Generated by Django 3.0.7 on 2020-09-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20200917_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='locationType',
            field=models.CharField(default='', max_length=10, verbose_name='Location Type'),
        ),
    ]
