# Generated by Django 3.0.7 on 2020-09-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_auto_20200917_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='nondom',
            field=models.BooleanField(default=False),
        ),
    ]
