# Generated by Django 3.0.7 on 2020-09-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_sign_nondom'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='motionType',
            field=models.CharField(default='split', max_length=10, verbose_name='Motion Type'),
        ),
        migrations.AddField(
            model_name='sign',
            name='outofphase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sign',
            name='symmetry',
            field=models.CharField(default='split', max_length=7, verbose_name='Symmetry'),
        ),
    ]
