# Generated by Django 3.0.7 on 2020-09-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_auto_20200918_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='locationType',
            field=models.CharField(default='', max_length=20, verbose_name='Location Type'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='motionType',
            field=models.CharField(default='split', max_length=20, verbose_name='Motion Type'),
        ),
    ]
